---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: spring-boot-demo-depl
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: spring-boot-demo
 template:
  metadata:
   name: spring-boot-demo-pod
   labels:
     app: spring-boot-demo 
  spec: 
    containers:
    - name: spring-boot-demo-container
      image: spring-boot-demo:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: spring-boot-demo-service
spec:
  type: NodePort
  selector:
   app: spring-boot-demo
  ports:
   - port: 80
     targetPort: 8080
...
